query CategoriesByUrl($where: JSON) {
  categories(where: $where) {
    id
    name
    url
    image {
      url
    }
    parentCategory {
      id
      name
      url
      image {
        url
      }
      parentCategory {
        id
        name
        url
        image {
          url
        }
      }
    }
  }
}